# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenCVGui
email: david.millan@damiles.com
description: > # this means to ignore newlines until "baseurl:"
  OpenCVGUI is a new graphical user inteface for OpenCV with different widgets
  and tools to provide developers a new and more powerful user interface
  with 3D and 2D plotting support, advanced forms, with small dependencies and OpenGL based.
baseurl: "/OpenCVGUI" # the subpath of your site, e.g. /blog
url: "http://damiles.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: damiles3D
github_username:  damiles

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: blog
    type: pages
  values:
    sectionid: blog
- scope:
    path: tutorial
    type: pages
  values:
    layout: tutorial
    sectionid: tutorial
- scope:
    path: docs
    type: pages
  values:
    layout: docs
    sectionid: docs
- scope:
    path: contributing
    type: pages
  values:
    sectionid: docs
- scope:
    path: community
    type: pages
  values:
    layout: community
    sectionid: community


# Build settings
highlighter: rouge
markdown: kramdown
# theme: minima

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
opencvgui_version: 0.1